@startuml
'https://plantuml.com/class-diagram

interface EnemyAircraftFactory{
    + creatEnemyProduct():EnemyAircraftProduct
}

interface EnemyAircraftProduct{
    + createliteenemy():EliteEnemy
    + creatmobnemy():MobEnemy
    + creatbossenemy():BossEnemy
}

EnemyAircraftProduct <|.. EliteEnemyProduct
EnemyAircraftProduct <|.. MobEnemyProduct
EnemyAircraftProduct <|.. BossEnemyProduct

EnemyAircraftFactory <|.. CreatEliteEnemy
EnemyAircraftFactory <|.. CreatMobEnemy
EnemyAircraftFactory <|.. CreatBossEnemy

CreatMobEnemy <.. MobEnemyProduct
CreatEliteEnemy <.. EliteEnemyProduct
CreatBossEnemy <.. BossEnemyProduct

class CreatEliteEnemy{
    + creatEnemyProduct():EnemyAircraftProduct
}

class CreatMobEnemy{
    + creatEnemyProduct():EnemyAircraftProduct
}

class CreatBossEnemy{
    + creatEnemyProduct():EnemyAircraftProduct
}

class MobEnemyProduct {
    + creatmobnemy():MobEnemy
    + createliteenemy():EliteEnemy
    + creatbossenemy():BossEnemy
}

class EliteEnemyProduct {
    + createliteenemy():EliteEnemy
    + creatmobnemy():MobEnemy
    + creatbossenemy():BossEnemy
}

class BossEnemyProduct{
    + createliteenemy():EliteEnemy
    + creatmobnemy():MobEnemy
    + creatbossenemy():BossEnemy
}

@enduml