@startuml
'https://plantuml.com/class-diagram

class HeroAircraft {
    - shootNum:int
    - power:int
    - direction:int
    + heroAircraft:HeroAircraft
    + HeroAircraft(int locationX, int locationY, int speedX, int speedY, int hp)
    + forward():void
    + shoot():List<BaseBullet>
    + getHeroAircraft():HeroAircraft
}

@enduml